spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    customer-api:
      path: /customer-api/**
      url: http://localhost:8300
    crm-service:
      path: /crm-service/**
      url: http://localhost:8083